default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: redux_test_api_dev

test:
  <<: *default
  database: redux_test_api_test

production:
  <<: *default
